apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: entsrzx2z-nodejs 
  janus-idp.io/tekton: entsrzx2z-nodejs
  backstage.io/kubernetes-id: entsrzx2z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: entsrzx2z-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml